### ISSUE TITLE
Bower asks me to choose versions

### ISSUE THREAD

**Issue by houshuang** [LRNWebComponents/app-editor-hax#1]
Have not worked with Bower before, but when I tried running Bower in this directory, it gave me tons of choices between different versions, where I did not know what to answer.

**Comment by btopro** [comment]
Everything latest except polymer, 1.x.x for that and webcomponentsjs, 0.7.24 for that.

I'll have to have it force resolution in dependencies to try and clean that up.

**Comment by btopro** [comment]
should autoresolve now
